language: java
install: true
jdk: oraclejdk8
dist: trusty
sudo: true
before_install:
  - chmod +x mvnw
stages:
  - compile
  - test
cache:
  directories:
    - .autoconf
    - $HOME/.m2
spring:
  datasource:
    url: ${jdbc:h2:mem:testdb}
    username: ${admin1}
    password: ${password1}

deploy:
  provider: heroku
  api_key:
    secure: "636201b9-33d9-4496-891e-1fd3090612a3"
  app: secure-headland-72344
  on:
      repo: EkoGroszek/RestApiTest
