language: java
install: true
jdk: oraclejdk8
dist: trusty
sudo: true
before_install:
  - chmod +x mvnw
stages:
  - compile
  - test
cache:
  directories:
    - .autoconf
    - $HOME/.m2
  deploy:
    provider: heroku
    api_key:
      secure: c212d231-acb8-4eae-b130-ff5141f575a2
    app: bankrestapicomarch
    on:
      repo: EkoGroszek/RestApiTest
